version: '3'
services:
  frontend:
    command: sh -c "npm rebuild esbuild && npm run dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount the local 'frontend' directory into the '/app' directory in the container
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - database
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./backend:/app  # Mount the local 'backend' directory into the '/app' directory in the container

  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=expensetracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:  # Create a named volume for the database data
