version: '3'
services:
  frontend:
    command: sh -c "npm rebuild esbuild && npm run dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount the local 'frontend' directory into the '/app' directory in the container
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database

    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:6433/expensetracker
      NODE_ENV: development
      PORT: 4000
    volumes:
      - ./backend:/app  # Mount the local 'backend' directory into the '/app' directory in the container

  database:
    image: postgres
    ports:
      - "6433:6433"
    environment:
      - POSTGRES_DB=expensetracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:  # Create a named volume for the database data
