version: '3'
services:
  frontend:
    command: sh -c "npm rebuild esbuild && npm run dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount the local 'frontend' directory into the '/app' directory in the container
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5433
      - DB_USER=dkupinic
      - DB_PASSWORD=123
      - DB_NAME=expense_tracker
    volumes:
      - ./backend:/app  # Mount the local 'backend' directory into the '/app' directory in the container

  database:
    image: postgres
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_DB=expensetracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:  # Create a named volume for the database data