version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount the local 'frontend' directory into the '/app' directory in the container

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5433
      - DB_USER=dkupinic
      - DB_PASSWORD=123
      - DB_NAME=expense_tracker
    volumes:
      - ./backend:/app  # Mount the local 'backend' directory into the '/app' directory in the container

  database:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=dkupinic
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=expense_tracker
    volumes:
      - database_data:/var/lib/postgresql/data  # Mount the database data directory to enable data persistence

volumes:
  database_data:  # Create a named volume for the database data